# Generated by Django 2.0.7 on 2018-07-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=50)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(help_text='Nombre del empleado', max_length=50)),
                ('apellido_emp', models.CharField(help_text='Apellido del empleado', max_length=50)),
                ('no_identidad', models.CharField(help_text='Numero de identidad del empleado', max_length=20)),
                ('fecha_nac', models.CharField(help_text='Fecha de nacimiento del empleado', max_length=20)),
                ('telefono', models.CharField(help_text='Numero telefonico del empleado', max_length=20)),
                ('telefono_emerg', models.CharField(help_text='Telefono de emergencia', max_length=20)),
                ('direccion', models.CharField(help_text='Direccion del empleado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Nombre del producto', max_length=50)),
                ('cant_producto', models.CharField(help_text='Cantidad existente del producto', max_length=50)),
                ('existe', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Ingrese el producto', max_length=50)),
                ('precio', models.CharField(help_text='Precio del producto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Nombre de la empresa', max_length=50)),
                ('telefono', models.CharField(help_text='Numero telefonico de la empresa', max_length=50)),
            ],
        ),
    ]
